# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    console.app.test:
        class: AppBundle\Command\ProcessTest
        tags:
            - { name: console.command }

